import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:kureselproje_app/screens/countries/ulkeler/almanya/almanya.dart';
import 'package:kureselproje_app/screens/anasayfa_routes/populer_kategori/gfp_endeksi.dart';

List<genelsiralama2021> index0 = [
  genelsiralama2021(
    almanya(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  //5.
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.north_outlined,
    Colors.green,
  ),
  //10
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.south_outlined,
    Colors.red,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.south_outlined,
    Colors.red,
  ),
  //15
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.north_outlined,
    Colors.green,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.south_outlined,
    Colors.red,
  ),
  //20
  genelsiralama2021(
    gfp_endeksi(),
    Icons.north_outlined,
    Colors.green,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.north_outlined,
    Colors.green,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.swap_horiz_outlined,
    Colors.grey,
  ),
  genelsiralama2021(
    gfp_endeksi(),
    Icons.north_outlined,
    Colors.green,
  ),
];

class genelsiralama2021 {
  final yolu;
  IconData icon;
  Color color;

  genelsiralama2021(
    this.yolu,
    this.icon,
    this.color,
  );
}
